### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jacobhands** [sssamarillo/imflow#1]
#### 0.0.0

- [ ] Create ERD targeting SQL
- [ ] Create end user workflow diagram
- [ ] Create program workflow diagram

#### 0.0.1

- [ ]
